### ISSUE TITLE
Your code don't work...

### ISSUE THREAD

**Issue by Scienceseb** [pmorerio/admd#3]
I always get that -
--Do not forget to rename the variables in the orginal resnet checkpoint if you are training for the first time
---Run rename_ckpt.sh
Loading pretrained rgb/resnet50...
[]
Traceback (most recent call last):
  File "/media/seb/SSD2/master/comparaison/admd/NYUD/main.py", line 19, in <module>
    solver.train_single_stream(modality='rgb')
  File "/media/seb/SSD2/master/comparaison/admd/NYUD/solver.py", line 143, in train_single_stream
    restorer=tf.compat.v1.train.Saver(variables_to_restore)
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 862, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

yes I have run the rename_ckpt.sh succesfully. So there is No variables to save in variables_to_restore at the beginning

**Comment by pmorerio** [comment]
Hi.
Can you please print `variables_to_restore`? I believe it is not empty as you suggest.
Are you giving the correct path for  `resnet50_ckpt`? Deafault is the string `'/data/models/resnet_50/'`, which of course does hold for my machine only.
Best,
P.

**Comment by Scienceseb** [comment]
That was not the right error, sorry I'm able to load the model with that (I just want the RGB part single stream):
        with tf.compat.v1.Session() as sess:
            saver = tf.compat.v1.train.import_meta_graph(
                '/media/seb/SSD2/master/comparaison/admd/data/models/resnet_50/resnet_v1_50_rgb.ckpt.meta')
            saver.restore(sess, "/media/seb/SSD2/master/comparaison/admd/data/models/resnet_50/resnet_v1_50_rgb.ckpt")
That loaded the model.

But the problem is even with that modification, I still got an error with the model, it's seem that the model which is a multimodal object has no attributes images...

Traceback (most recent call last):
  File "/media/seb/SSD2/master/comparaison/admd/NYUD/main.py", line 19, in <module>
    solver.train_single_stream(modality='rgb')
  File "/media/seb/SSD2/master/comparaison/admd/NYUD/solver.py", line 144, in train_single_stream
    feed_dict = {self.model.images: self.dataset['train'][modality + '_images'][i * self.batch_size:(i + 1) * self.batch_size],
AttributeError: 'MultiModal' object has no attribute 'images'

with a simple verification print(self.model.images) after the self.model.build_model() I got the same error

Thank you for your help we would love to cited your work in our upcoming paper so we need that to work.

**Comment by Scienceseb** [comment]
> Hi.
> Can you please print `variables_to_restore`? I believe it is not empty as you suggest.
> Are you giving the correct path for `resnet50_ckpt`? Deafault is the string `'/data/models/resnet_50/'`, which of course does hold for my machine only.
> Best,
> P.

No it

**Comment by pmorerio** [comment]
I am sorry, but `feed_dict = {self.model.images: self.dataset['train'][modality + '_images'][i * self.batch_size:(i + 1) * self.batch_size]` is at line 155 not 144. https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/solver.py#L155
What happened to the previous lines? If you work with a modified version of the code it is very hard to help you. 

Inside the function `self.model.build_model()`, you should enter the first `if` block, since you are training a single rgb stream. `images` is a placeholder defined at line at line 113 https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/model.py#L113

Please verify that your code correctly builds the placeholder. Indentation issues may also prevent some lines to be run.

Hope this helps.

**Comment by Scienceseb** [comment]
> I am sorry, but `feed_dict = {self.model.images: self.dataset['train'][modality + '_images'][i * self.batch_size:(i + 1) * self.batch_size]` is at line 155 not 144.
> 
> https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/solver.py#L155
> 
> 
> What happened to the previous lines? If you work with a modified version of the code it is very hard to help you.
> Inside the function `self.model.build_model()`, you should enter the first `if` block, since you are training a single rgb stream. `images` is a placeholder defined at line at line 113
> 
> https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/model.py#L113
> 
> Please verify that your code correctly builds the placeholder. Indentation issues may also prevent some lines to be run.
> 
> Hope this helps.

 I just change the loading of the model this doesn't change anything I hard code to load the RGB model because I never want the depth model for my work. But the error is before this modification it's with the build_model...so yes you were right it was in indentation problem with the code..

Still the rest of the code is not working...so Im thinking probasbly an error with the loading of the model

Maybe you are right my modification before is not good so right know I'm trying to make   variables_to_restore = slim.get_model_variables(scope='xxx') work to use exactly the same code as you. 

Right now its seem to work because my print(variables_to_restore ) gives [<tf.Variable 'None/resnet_v1_50/conv1/weights:0' shape=(7, 7, 3, 64) dtype=float32_ref>, <tf.Variable 'None/resnet_v1_50/conv1/BatchNorm/gamma:0' shape=(64,) dtype=float32_ref>, <tf.Variable 'None/resnet_v1_50/conv1/BatchNorm/beta:0' shape=(64,) ....etc]. 

**But there is still an error with the loading:  at the line restorer.restore(sess,"/media/seb/SSD2/master/comparaison/admd/data/models/resnet_50/resnet_v1_50_rgb.ckpt")**  : tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error: tensorflow.python.framework.errors_impl.NotFoundError: Key None/resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
	 [[{{node save/RestoreV2}}]]

**Comment by pmorerio** [comment]
Hi. Make sure you are not trying to restore `f_repr` and `logits`. They are not in the checkpoint. Please cf. lines 136-140 in `solver.py` where I remove them from the list `variables_to_restore`.

**Comment by Scienceseb** [comment]
> Hi. Make sure you are not trying to restore `f_repr` and `logits`. They are not in the checkpoint. Please cf. lines 136-140 in `solver.py` where I remove them from the list `variables_to_restore`.

Ok I cf. lines 136-140 but still I got the same error (tensorflow.python.framework.errors_impl.NotFoundError: Key None/resnet_v1_50/_logits_/biases not found in checkpoint [[{{node save/RestoreV2}}]]) with the line 142 restorer.restore(sess,"/media/seb/SSD2/master/comparaison/admd/data/models/resnet_50/resnet_v1_50_rgb.ckpt") Just to be sure of what the resnet-50 folder need to contain for RGB to work: I got resnet_v1_50.ckpt, resnet_v1_50_rgb.ckpt.data-00000-of-00001, resnet_v1_50_rgb.ckpt.index, resnet_v1_50_rgb.ckpt.meta.

**Comment by pmorerio** [comment]
Hi, as I said it is difficult to help with your modified version of the code.

From what I can see, you are trying to restore the variable `None/resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta` which is **OBVIOUSLY** not found in the checkpoint, since every variable in the rgb checkpoint has the form `rgb/resnet_v1_50`. So you are failing to give the correct modality argument to the function `train_single_stream(self, modality)`. When creating the `variable_to_restore` list, you are appending `None` at the beginning of variables names instead of `rgb`.

**Comment by Scienceseb** [comment]
> Hi, as I said it is difficult to help with your modified version of the code.
> 
> From what I can see, you are trying to restore the variable `None/resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta` which is **OBVIOUSLY** not found in the checkpoint, since every variable in the rgb checkpoint has the form `rgb/resnet_v1_50`. So you are failing to give the correct modality argument to the function `train_single_stream(self, modality)`. When creating the `variable_to_restore` list, you are appending `None` at the beginning of variables names instead of `rgb`.

Ok so If i understand I have to put the scope to rgb in for the variable right ? I have exactly the same code as you, the only différence is variables_to_restore = slim.get_model_variables(scope='xxx'), I dont know what xxx should be...How can I change the None to RGB ? My problem seem to be when I put variables_to_restore = slim.get_model_variables() I got the variable list ('None/resnet_v1_50/conv1/weights:0' shape=(7, 7, 3, 64) dtype=float32_ref...) but with None at the beginning and when I put variables_to_restore = slim.get_model_variables(scope='rgb'+ ‘/resnet_v1_50’), I got an empty variable list [ ], same thing if the scope is just "rgb", just that was my original problem here I got an empty list for variable when I run eaxctly your code.

**Comment by pmorerio** [comment]
The problem is not `variables_to_restore`. The problem is that you screwed up the code in a way that no `modality` argument is given to the `single_stream` function in `model.py`. Thus you are building a graph where the scope is `None` when you create a single stream network in the `build _model` function ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/model.py#L117)).

**Comment by Scienceseb** [comment]
Ok If you think I screwed up the code **I’m gonna restart from zero with your original code**, but for that I will need from you to know exactly **what your folder resnet_50 contain** and **what do you modify from line 128 to 144 in solver.py** to make it work  if I’m training for the first time. If you are right and your code is working this issue should close after that help from you. **Thanks a lot for your help.**

**Comment by pmorerio** [comment]
Ok let me recap.

As you said, after running the rename checkpoint utility you must have 
resnet_v1_50.ckpt, 
resnet_v1_50_rgb.ckpt.data-00000-of-00001, 
resnet_v1_50_rgb.ckpt.index,
resnet_v1_50_rgb.ckpt.meta

All the variables in this checkpoint has the form `rgb/resnet_v1_50/xxxx`.
But the checkpoint is not the problem.

When `build_model` is called in the code, the requested modality is taken as scope ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/model.py#L27)), thus all the variables created in the tensorflow graph have a name like  `rgb/resnet_v1_50/xxxx`, _precisely as in the checkpoint_. This way the saver can restore all the variables. If your variables have the name `None/resnet_v1_50/` there is something wrong!
If you are giving the correct option `--mode train_rgb` in the main everything should be fine, since a model is created with `self.mode='train_rgb'` ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/main.py#L15)). Then, after you build the model the `modality` variable is created containing the string `rgb` ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/model.py#L112)) which is used as scope in the `single_stream` function.

In your case, for some reason, the scope `None` is created, probably because the main is taking the  default flag `None` ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/main.py#L6)). Are you giving the correct flag when running the main (cf [here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/run.sh#L2))?

**Comment by Scienceseb** [comment]
> Ok let me recap.
> 
> As you said, after running the rename checkpoint utility you must have
> resnet_v1_50.ckpt,
> resnet_v1_50_rgb.ckpt.data-00000-of-00001,
> resnet_v1_50_rgb.ckpt.index,
> resnet_v1_50_rgb.ckpt.meta
> 
> All the variables in this checkpoint has the form `rgb/resnet_v1_50/xxxx`.
> But the checkpoint is not the problem.
> 
> When `build_model` is called in the code, the requested modality is taken as scope ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/model.py#L27)), thus all the variables created in the tensorflow graph have a name like `rgb/resnet_v1_50/xxxx`, _precisely as in the checkpoint_. This way the saver can restore all the variables. If your variables have the name `None/resnet_v1_50/` there is something wrong!
> If you are giving the correct option `--mode train_rgb` in the main everything should be fine, since a model is created with `self.mode='train_rgb'` ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/main.py#L15)). Then, after you build the model the `modality` variable is created containing the string `rgb` ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/model.py#L112)) which is used as scope in the `single_stream` function.
> 
> In your case, for some reason, the scope `None` is created, probably because the main is taking the default flag `None` ([here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/main.py#L6)). Are you giving the correct flag when running the main (cf [here](https://github.com/pmorerio/admd/blob/754d5cc8d3aeae252a5c2cb16f66d5aac2d31de6/NYUD/run.sh#L2))?

**### If I uncommented the line 136-140 its working!** 

Ok this time **I didnt modify your code at all, not one line**, I just change the path to for the data and models (at line 14-15) and cf. lines 136-140 like you said to do before, **this time it's no None but RGB so that's fix** but **still the code is not running I got the same type of error**: 

Traceback (most recent call last):
  File "/media/seb/SSD2/master/comparaison/admd/NYUD/main.py", line 18, in <module>
    solver.train_single_stream(modality='rgb')
  File "/media/seb/SSD2/master/comparaison/admd/NYUD/solver.py", line 146, in train_single_stream
    'resnet_v1_50_' + modality + '.ckpt')
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key rgb/resnet_v1_50/_logits_/biases not found in checkpoint
	 [[node save/RestoreV2 (defined at media/seb/SSD2/master/comparaison/admd/NYUD/solver.py:144) ]]

**### If I uncommented the line 136-140 its working!**

**Comment by pmorerio** [comment]
I am sorry, I never said you should comment lines 136-140...i said compare lines 136-140.
https://www.wordreference.com/definition/cf.

**Comment by Scienceseb** [comment]
> I am sorry, I never said you should comment lines 136-140...i said compare lines 136-140.
> https://www.wordreference.com/definition/cf.

You are totally right I misread you sorry for that.

**Comment by pmorerio** [comment]
No problem, happy to help :)
